### ISSUE TITLE
Problem to add calendar in iPhone 

### ISSUE THREAD

**Issue by jackermann** [jshor/datebook#53]
hi,

i have the problem to add icalendar on me iPhone, is there already an approach to solve this?

kind regards 
julian

**Comment by jwhazel** [comment]
I have found a temporary solution to this. I don't want to do a PR just yet because I'm not completely sure of the ramifications of this change:

https://github.com/jshor/angular-addtocalendar/blob/master/src/utils/utils.js#L85
Change `application/octet-stream` to `text/calendar`

Observed behavior:
* iOS 11.2 Safari - a new tab opens asking if you want to add an event to your calendar. Approving the dialog goes straight to the calendar with the event as desired.
* OSX Chrome 64 - downloads ics file as normal
* OSX Safari 11 - downloads ics file as normal


Possible improvements:
* Use user agent sniffing to determine iOS and _don't_ pass the file off to Filesaver. Instead, create a custom function that opens a file with the data: This has the same exact behavior as above except that it bypasses the modal asking for approval in mobile Safari and takes you straight to the calendar app (sweet!) I have a working model of that here: https://jsfiddle.net/jwhazel/h0p9n52h/
* Figure out what exactly the Addevent folks are doing over here: https://www.addevent.com/add-to-calendar-button. That uses a server side component to generate the .ics file. _But_ it has the interesting side effect of when using it Safari 11 on the desktop, the downloaded file immediately opens Calendar and prompts you to add the event (does not do this in Chrome). I haven't yet investigated to see how they accomplish this.

**Comment by jshor** [comment]
Thanks for opening the issue and the investigation on this.

* I implemented @jwhazel's suggestion [to do browser sniffing for Safari](https://github.com/jshor/datebook/blob/master/src/utils/ics.js#L96-L107). This will cause the MIME type of the ICS file to be [`text/calendar`](https://github.com/jshor/datebook/blob/master/src/utils/safariFileSave.js) instead of `application/octet-stream` for other browsers.

* Addevent is probably opening a link with a protocol to open the calendar app on the user's phone. Something like this might accomplish that:

```js
if (/iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream) {
  // iOS
  window.location.href = 'calshow:'
} else if (navigator.userAgent.toLowerCase().includes('android')) {
  // Android
  window.location.href = 'content://com.android.calendar/time/'
}
```

**Comment by jshor** [comment]
Ultimately, I've decided not to implement the aforementioned solution for opening the calendar app automatically in Android. The OS behavior of handling ICS files is outside of the scope of this package.

Since the original Safari issue seems to have been resolved with the MIME type update, I'm closing this issue.

**Comment by maryamaljanabi** [comment]
Hi @jshor I'm having the same problem for iPhone, the generated .ics doesn't open. Can you please tell me how to change the MIME type for the iCalendar variable before downloading the .ics? I looked in the [documentation for iCalendar generation](https://datebook.dev/docs/icalendar.html) but didn't find a way.
Thanks in advance.

**Comment by maryamaljanabi** [comment]
Hi @jshor I'm having the same problem on chrome iPhone (on Safari it works) and I tried changing the MIME type but it didn't work. Is there something else that I can try? I appreciate any advice that you can give me.

**Comment by jshor** [comment]
@maryamaljanabi unfortunately there is no way that I know of to control how the client interacts with the ICS file (besides possibly changing its MIME type).
